### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by brugnara** [geejs/gulp-tap#3] opened 2014-08-06 08:53 UTC
See inline comments below:

``` js
var replace = require('gulp-replace');

gulp.task('less', function () {
  return gulp.src(['./projects/**/style/main.less', '!./projects/_*/**', '!./projects/.*/**'])
    .pipe(tap(function(file, t) {
      var prj = file.path.replace(file.base, '').split('/')[0];
      console.log(prj);
      console.log(currentPath);
      // Both generate an infinite loop, dunno why.
      t.through(replace, [/PUBLIC/g, currentPath]);
      // return t.through(replace(/PUBLIC/g, currentPath));
    }))
    .pipe(less())
    .pipe(gulp.dest('./dist'));
});
```

**Comment by dougalg** [comment] 2015-03-23 14:46
I have encountered this problem while using Babel as well:

    return gulp.src(__src +'js/**/*.{js,tpl}')
        .pipe(tap(function(file, t) {
            if (path.extname(file.path) === '.js') { return t.through(babel, []); }
        }))
        .pipe(gulp.dest((debug ? __dst : __tmp) +'js'));

This gives an infinite loop of the first JS file. If I remove the `return` statement, then it loops over all files forever.

**Comment by mattflix** [comment] 2016-05-26 03:27
+1

I am also seeing infinite looping (on the first file) when trying to "tap" the output of gulp-babel.

**Comment by lalarsson** [comment] 2016-09-29 13:16
+1
I'm getting it with gulp-mustache.

**Comment by JacobDB** [comment] 2017-01-30 16:04
I'm having this problem as well, it appears to be something with `through` causing the loop.

**Comment by dotnetCarpenter** [comment] 2017-04-07 10:10
If someone can write a unit test that confirms this, then I'll fix it. But since I don't know what the problem is and all the examples here requires lots of other gulp plugins, it's hard to write a test that can confirm or invalidate this issue.

**Comment by dotnetCarpenter** [comment] 2017-04-07 15:45
Please test again with the [latest release](https://github.com/geejs/gulp-tap/releases).

**Comment by dotnetCarpenter** [comment] 2017-05-02 13:47
@brugnara, @cferdinandi, @wadi-chemkhi, @dougalg, @mattflix, @lalarsson and @JacobDB. Do you have a link to your old code that broke? If yes, can you post it here, so I can create a test-case?

I'm closing this for now, until I get further information.

**Closed by dotnetCarpenter** 2017-05-02 13:47 UTC
Labels: test:needed
